### ISSUE TITLE
onVideoTrackRemoved not called onParticipantDisconnected

### ISSUE THREAD

**Issue by antross** [twilio/video-quickstart-android#125]
Using Twilio Video SDK 1.0.2 for Android.

I have UI elements I need to dispose of when a video track is removed. However when `onParticipantDisconnected` fires, the `participant.getVideoTracks()` collection is already empty, yet I never received any calls to `onVideoTrackRemoved`.

The effect on my UI is very similar to #83, though that was resolved well before this build and may have a different root cause.

I can of course track these objects myself and plan to as a workaround, but filing as a bug since I would expect either the video tracks collection on the participant to still be populated during `onParticipantDisconnected` or calls to be made to `onVideoTrackRemoved` under these conditions.

**Comment by aaalaniz** [comment]
Hey @antross 

Thanks for writing in. This is a bug in our SDK and I will begin working on a fix. The expected behavior should be that the audio and video tracks are available on the `Participant` even after the disconnect event is fired. This will allow you to clean up your UI elements accordingly. As a workaround, you can maintain a set of video tracks for each participant and clean up the UI elements for those video tracks once the participant disconnects.

We have a `1.0.3` release pending. Expect the fix for this bug to be in `1.0.4`. 

Thanks!

**Comment by aaalaniz** [comment]
Correction. We have a `1.1.0` release pending. Expect the fix for this bug to be in `1.1.1`

Thanks!

**Comment by antross** [comment]
Great, thanks for the quick response! 

I'll move forward with the workaround and look forward to deleting some code once the fix is available. :)

**Comment by aaalaniz** [comment]
Hey @antross 

We rolled this bug fix into our `1.1.0` release. We are doing final tests on this release tonight. I will notify you when it is available.

Thanks for your patience.

**Comment by aaalaniz** [comment]
Hey @antross ,

This bug has been fixed in `1.1.0`.

Thanks for reporting it!
