### ISSUE TITLE
Disconnect Video call Without pick

### ISSUE THREAD

**Issue by mvctest17** [twilio/video-quickstart-android#170]
Hi,

When I am disconnecting the video call without joining the room then it is not disconnecting the call on other person device. Please help me out.

Thanks

**Comment by aaalaniz** [comment]
Hey @mvctest17 

Are you saying that if you call `room.disconnect()` before connecting to a `Room` another participant connecting to that same room is not able to connect? Please provide logs, code snippets, or any other information that clarify the issue. What version of the Android SDK are you using?

Thanks!

**Comment by mvctest17** [comment]
Hi @aaalaniz 

I am using Android SDK version 25.

Thanks!

**Comment by aaalaniz** [comment]
Hey @mvctest17 

If you disconnect before connecting to the Room then the other participant will not receive an `onParticipantDisconnected` callback because the participant never connected. If you need to check if there is participant in a Room after connect you can invoke `room.getParticipants` after you have connected.

Let me know if this helps.

Thanks!

**Comment by mvctest17** [comment]
Hi @aaalaniz 

Thanks for your help. I have to create service in server side to send notification so that other participant came to know that video call disconnected or is a missed call. 

Thanks!

**Comment by aaalaniz** [comment]
Happy to help @mvctest17 

I will close this issue. Please open another issue if you have further questions.

Thanks!
