### ISSUE TITLE
How to turn on the flash?

### ISSUE THREAD

**Issue by TalbotGooday** [twilio/video-quickstart-android#171]
I've found that there is no way to turn on the flash on camera 'cause there is no way to get encapsulated camera object. Is there a way to do this. If not, is it planned to implement it?

**Comment by adolmatovs** [comment]
I believe you are looking for [this](https://github.com/twilio/video-quickstart-android/blob/master/exampleAdvancedCameraCapturer/src/main/java/com/twilio/video/examples/advancedcameracapturer/AdvancedCameraCapturerActivity.java#L60)

**Comment by TalbotGooday** [comment]
Thank you so much

**Comment by spatel-connect2d** [comment]
https://github.com/PDDStudio/easyflashlight
Just use this in your Gradle and create the object right when you connect to the room. There is a listener that is called after connecting to the room. Initialize it there and it will work. This is better because it works on older devices as well as newer ones.
