### ISSUE TITLE
Video Lifecycle Documentation for 2.X

### ISSUE THREAD

**Issue by mcorner** [twilio/video-quickstart-android#183]
We are migrating from 1.x to 2.x.  There is a lack of documentation about the lifecycle of events with video tracks.  In 2.x it is even more confusing.  There seem to be four places where we might get a new video stream (we have a simple, two participant system).  It is unclear in what order they get fired and in response to what events on the other side.

- addParticipant
- onVideoTrackPublished
- onVideoTrackEnabled
- onVideoTrackSubscribed

Some documentation (other than the sample code) would be quite helpful.

**Comment by aaalaniz** [comment]
Hey @mcorner 

I completely agree that our lack of official docs for 2.x is frustrating. A migration guide is being put together by our team and hopefully will be done in the coming weeks.. In addition to the [2.0 branch](https://github.com/twilio/video-quickstart-android/tree/2.0) on the quickstart we do have [API docs](https://media.twiliocdn.com/sdk/android/video/releases/2.0.0-preview4/docs/) available for the 2.x releases. In the meantime, I will field your questions about the new API. 

### Track Publications
We have introduced the notion of publishing audio, video, and data tracks in 2.x. You can think of a track publication as a representation of your track on our signaling server. 

### Track Subscriptions
Track subscriptions represent the state at which participant's have negotiated and media is actually flowing to a participant. This is an important distinction from a publication because it allows developer's to think of the media from a track as something to option into. In our current 2.x beta releases we do **not** support selecting which tracks you subscribe to, but we are actively working toward this functionality. We refer to the track subscription policy shipped today as "Auto Subscription" where every track that is published is automatically subscribed to. Auto subscription is the only supported policy in a P2P Room and like I said, we are actively marching towards developer's being able to select which tracks they subscribe to in a Group Room.

### Track Events
Let's take the scenario of Alice and Bob being connected to the same Room and Alice publishes a video track to answer your questions about ordering.

1. Alice publishes video track to Room
2. Alice receives LocalParticipant.Listener#onVideoTrackPublished callback
3. Bob receives RemoteParticipant.Listener#onVideoTrackPublished
4. Bob receives RemoteParticipant.Listener#onVideoTrackSubscribed (Alice's video track is now flowing to Bob)
5. Alice calls `LocalVideoTrack#enable(false)`
6. Bob receives RemoteParticipant.Listener#onVideoTrackDisabled
7. Alice calls `LocalVideoTrack#enable(true)`
8. Bob receives RemoteParticipant.Listener#onVideoTrackEnabled
9. Alice unpublished video track
10. Bob receives RemoteParticipant.Listener#onVideoTrackUnsubscribed (Alice's video track media is no longer flowing to Bob)
11. Bob receives RemoteParticipant.Listener#onVideoTrackUnpublished

I know this isn't perfect, but I hope it's helpful in understanding some of the new 2.x APIs. I'd be happy to field any follow-up.

Thanks!

**Comment by mcorner** [comment]
Yes, this is good!  It would be great to stick it in the official docs of course.

**Comment by idelgado** [comment]
@mcorner we recently published the first set of documentation for 2.X https://www.twilio.com/docs/api/video/android-v2-getting-started

We still have lots of work to do on this front with more content that describes API behavior and a migration guide from 1.X to 2.X.

Thanks again for the feedback.

**Comment by aaalaniz** [comment]
Hey @mcorner 

Another update on 2.x documentation. We recently shipped a [1.x to 2.x migration guide](https://www.twilio.com/docs/api/video/migrating-1x-2x-android-20) that provides an introduction to the 2.x SDK as well as migration guidance. I will leave this ticket open because we still have some docs tasks open about explaining why developers should consider switching to 2.x and how it can help their use cases.

Thanks!

**Comment by aaalaniz** [comment]
Closing this issue as we have added more documentation about the [features available in 2.x](https://www.twilio.com/docs/video/android#migrating-from-1x-to-2x).

Thanks @mcorner!

**Comment by isMeCoder** [comment]
@aaalaniz, what's the latest on providing participants with the ability to subscribe select rooms in a Group Room? Do the various 2.x SDKs / APIs officially support it yet?
