### ISSUE TITLE
Listen for IncomingInvite via IntentService

### ISSUE THREAD

**Issue by donjerick** [twilio/video-quickstart-android#23]
Good day!

Would like to ask if there are any references or sample app that can help me work on listening for an incoming invite via an IntentService? I would like to notify the user that someone is trying to call him/her even when the app is not running. Is this possible?

**Comment by idelgado** [comment]
@donjerick I encourage you to try our new library which is in developer preview. One of the shortcomings of the conversations library, is that it required inviting. Inviting on Android is challenging even with a Service because the OS is free to kill the Service whenever it deems necessary.

In this developer preview, we no longer invite. Users join using a name to a Room. You are free to signal the room name to other participants with whatever you prefer(GCM, Firebase, etc.). The developer preview is available here (https://github.com/twilio/video-quickstart-android/tree/rooms) and we will be deprecating conversations in favor of this new library in the coming weeks as it goes into public beta.
