### ISSUE TITLE
help to notify particular user about attempt to create room by other user

### ISSUE THREAD

**Issue by iamjitendrasinh** [twilio/video-quickstart-android#237]
In this example all user receives notification about some user try to create room. is it possible if only particular user get notify when some user wants to create room?

**Comment by aaalaniz** [comment]
Hey @iamjitendrasinh 

You could use the tags feature of [Twilio Notify](https://www.twilio.com/notify/api) to accomplish this. Use a unique identifier of a user as a tag and have only that user register for notifications with that identifier. Then your calling user could send a notification to the unique identifier of the user they want to notify.

Happy to field any follow-up.

Thanks!

**Comment by idelgado** [comment]
Notify allows you to send notifications to specific identities as well as tags. In order to do this you will need to modify the existing sendNotification [model object](https://github.com/twilio/video-quickstart-android/blob/master/exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/notify/api/model/Notification.java) to have an `Identity` field. Once you've added the Identity field the [sdk-starter-java](https://github.com/TwilioDevEd/sdk-starter-java/blob/master/src/main/java/com/twilio/ServerApp.java#L174) will parse the field here and should notify the identity specified in the field.

Here is an example from the REST docs: https://www.twilio.com/docs/api/notify/rest/notifications#sending-to-stored-bindings

**Comment by idelgado** [comment]
Note that in order to notify a specific identity you don't need to specify a tag

**Comment by aaalaniz** [comment]
Hey @iamjitendrasinh

I'm closing this issue. Please reopen if you have further questions about using Notify with Video.

Thanks!
