### ISSUE TITLE
Disable LocalVideoTrack for RemoteParticipant only

### ISSUE THREAD

**Issue by ghost** [twilio/video-quickstart-android#304]
When calling enable(false) on a LocalVideoTrack it sends blank frames to both remote participant and your own local preview.

I'm trying to make it send blank frames to the remote participant only so that the user can still see what the camera is currently filming.

I tried to create two LocalVideoTracks one to stream to the RemoteParticipant and one to preview when the first one is disabled. This did not work since it seems the last track overrides the first so i would have to rejoin the room every time the camera is unmuted.

Is this possible to do with how Twilio works today?

**Comment by aaalaniz** [comment]
Hey @phsavisiba 

Can you elaborate on the use case you are trying to achieve?

Based on your description of the problem, you could unpublish the local video track you want to disable for the RemoteParticipant. This operation will result in the remote participant being unsubscribed from the video track without disabling the track locally.

I'm happy to field any follow up questions.

Thanks!

**Comment by phsavisiba** [comment]
@aaalaniz Hi

Use case example:
Two persons are having a video call lets call them A and B. A needs to temporarily mute the camera and presses a button which mutes the LocalVideoTrack. The result is that both A's VideoView for local camera is blank and B's VideoView for RemoteTrack is blank. But what i want to accomplish is to have A's LocalVideoView still displaying what the camera is filming while B's RemoteVideoView is still blank.

The reason is it is much nicer for A to see what the camera is filming before unmuting the LocalVideoTrack.

Unpublishing the track does indeed work from a purely technical perspective. The problem is that the wrong event will be sent to the remote participant. Muting and unpublishing events are handled completely different which is going to give the user misleading information.

This is of course not a big issue it would just be really nice if it could be implemented in some clever way.
