### ISSUE TITLE
when i try to get accesstoken using  AccessToken.Builder() its throw exception

### ISSUE THREAD

**Issue by sanjayrajsinh** [twilio/video-quickstart-android#348]
```  
 private fun retrieveAccessTokenfromServer() {
               var twilioAccountSid = "...";
                var twilioApiKey = "...";
                var twilioApiSecret = "....";
                var identity = "soun";

             // Create Video grant
                var grant = VideoGrant()
                grant.setRoom("DailyStandup");

                // Create access token
                var token = AccessToken.Builder(
                        twilioAccountSid,
                        twilioApiKey,
                        twilioApiSecret
                ).identity(identity).grant(grant).build();

Log.d(TAG,"--Token --"+token.toJwt()); //   **its throw exception** 

```
**build.gradle**
   implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation "com.android.support:preference-v14:28.0.0"
    implementation "com.android.support:design:28.0.0"
  implementation 'com.twilio.sdk:twilio:7.28.0' 
    implementation "com.twilio:video-android:3.0.0"
   
**Exception is** : Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl

**Comment by idelgado** [comment]
You should not generate the access token in the app. Someone could download your app, unpack it, and use your credentials since they are likely stored as strings in the resource section of the apk.

We recommend you use a web service to generate your access token and use your own auth mechanism to retrieve an access token whenever necessary.

As for the error, the Twilio Java helper library is not intended to be used on Android. It is intended for use in a server application.

Please see https://github.com/twilio/video-quickstart-android#setup-an-access-token-server for more information

**Comment by idelgado** [comment]
As stated in the other ticket that was filed using the Java helper library on Android is not supported. If you wish to use functionality related to this library you must use it in a server side application.

See https://www.twilio.com/docs/libraries/java for more information.

To use Programmable Video on Android you only need the following: `implementation "com.twilio:video-android:3.0.0"`.
