### ISSUE TITLE
How can I record local video and save it to file ?

### ISSUE THREAD

**Issue by bataemperor** [twilio/video-quickstart-android#458]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

How can I record local video and save it to file ?

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```java
// Code that help reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces how Often

[What percentage of the time does it reproduce?]

#### Logs

```
// Log output when issue occurs
```

### Versions

All relevant version information for issue.

#### Video Android SDK

[eg. 1.0.2]

#### Android API

[eg. 18]

#### Android Device

[eg. Nexus 5]

**Comment by aaalaniz** [comment]
Hey @bataemperor 

I am closing this issue due to lack of details. Please reopen with the issue template filled out and not applicable sections omitted. Provide the following details about your recording use case:

1. Do you want to record just one video track?
2. Do you need audio recorded as well? (do audio and video recordings need to be synchronized)
3. Is there a specific use case for local recording? We do offer [recordings](https://www.twilio.com/docs/video/api/recordings-resource) with participants connected to a Group room.

Thank you
