### ISSUE TITLE
Custom Camera Frames

### ISSUE THREAD

**Issue by TieuNhi95** [twilio/video-quickstart-android#514]
I have a problem which is needed for your support.

I want to process the frames before sending them to the remote side, such as insert emoji, icon, filter...
I'm trying to custom the Camera2Capturer but I can't. 
So, Could you give me a solution for this?
Note: I only want to edit on the local side then send it to the remote side, not edit on the remote side.

**Comment by aaalaniz** [comment]
Hey @TieuNhi95 

I recently answered a similar question in the [Video Collaboration app repo](https://github.com/twilio/twilio-video-app-android/issues/83#issuecomment-630427031). 

I suggest you try those recommended steps. Feel free to share an example project with us and we can take a look. I will close this issue for now as custom camera frames is not currently on our road map. However, we will be happy to provide assistance where possible.

Thanks!

**Comment by TieuNhi95** [comment]
@aaalaniz 
Thanks for support, i created an example project.

File CameraCapturerCompat : i copy from [https://github.com/twilio/video-quickstart-android/tree/master/quickstartKotlin](url)

File CustomCamera2Capture extends Camera2Capturer.

If i use CustomCamera2Capture, videoView is black. Can you help me?

My example : [https://github.com/TieuNhi95/CustomVideoFrame](url)

**Comment by TieuNhi95** [comment]
On VideoCapturer.Listener, i get a VideoFrame, but videoFrame.imageBuffer = null. So, i can't know how to custom videoFrame.

**Comment by TieuNhi95** [comment]
@aaalaniz can you help me?

**Comment by aaalaniz** [comment]
Hey @TieuNhi95 

After further investigation, this appears to be a lack of functionality in our SDK in that you do not have access to the texture id the camera capturers use to capture frames. You are observing a null image buffer, because the Twilio capturers upload frames to a texture. This API is only internal.

Unfortunately, extending the existing capturers for your use case will not be possible which leaves the only option of building your own custom capturer. I will leave this issue closed as adding the ability to capture to a texture is not on our roadmap.

Thank you.

**Comment by ken107** [comment]
Thank you for confirming that it's currently not possible.  I tried doing something similar, implementing a VideoCapturer that wraps Twilio's CameraCapturer.  Even though the wrapper simply passes through everything, it doesn't work.  I get the the following error:

`W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.postDelayed(java.lang.Runnable, long)' on a null object reference
        at tvi.webrtc.CameraCapturer.createSessionInternal(CameraCapturer.java:303)
        at tvi.webrtc.CameraCapturer.startCapture(CameraCapturer.java:297)
        at tvi.webrtc.Camera1Capturer.startCapture(Camera1Capturer.java:17)
        at com.twilio.video.CameraCapturer.startCapture(CameraCapturer.java:373)
        at com.lsdsoftware.homeportal.MyCameraCapturer.startCapture(MyCameraCapturer.kt:15)
        at com.twilio.video.VideoCapturerDelegate.startCapture(VideoCapturerDelegate.java:71)`

I'm guessing that CameraCapturer and its caller are implemented natively.  And adding a middleman in Java won't work, for reasons beyond my knowledge.

Anyway, I'm planning to use the latest Android CameraX ImageAnalysis use case, which will give me a YUV420 buffer directly.  Convert it into NV21 and pass it on to Twilio.  I hope it works 🤞

**Comment by ken107** [comment]
OK, it turns out due to the way the code is written, I must override CameraCapturer, not just wrap it.  But as mentioned by others in this thread, the _videoFrame.imageBuffer_ will be null because Twilio passes the actual frame via an internal variable named _webRtcVideoFrame_.  Using reflection, I'm able to access and modify it.  So, it works!  But obviously not a long-term solution.

```kotlin
override fun onFrameCaptured (videoFrame: VideoFrame) {
    videoFrame::class.java.getDeclaredField("webRtcVideoFrame")
        .let { field ->
            field.isAccessible = true
            field.set(videoFrame, process(field.get(videoFrame) as tvi.webrtc.VideoFrame))
        }
    listener?.onFrameCaptured(videoFrame)
}

private fun process (frame: tvi.webrtc.VideoFrame): tvi.webrtc.VideoFrame {
    return tvi.webrtc.VideoFrame(
        frame.buffer.cropAndScale(0, 0, frame.buffer.width, frame.buffer.height, myWidth, myHeight),
        frame.rotation,
        frame.timestampNs
    )
}
```

Here I use the built-in cropAndScale() method to scale it down to my desired width/height for my particular purpose.
