### ISSUE TITLE
How to disable tvi.webrtc.Logging

### ISSUE THREAD

**Issue by shahalRahman** [twilio/video-quickstart-android#604]
This is a question.

Using Android SDK version 5.13.0.

Application has become very hard to debug with the presents of tvi.webrtc.Logging. 
Is there a way to disable these logs ?

**Comment by Alton09** [comment]
The logs should be off by default, but you can also manually set them to off using the following:
```java
Video.setLogLevel(LogLevel.OFF);
```
If you are using Kotlin in your app, you can use Kotlin syntax instead using the new [ktx library](https://twilio.github.io/twilio-video-android/docs/ktx/latest/-video%20-android%20-k-t-x%206.1.0/com.twilio.video.ktx/-video/index.html#%5Bcom.twilio.video.ktx%2FVideo%2FlogLevel%2F%23%2FPointingToDeclaration%2F%5D%2FProperties%2F1674616256).

**Comment by marshallaf** [comment]
I also had this problem - `Video.setLogLevel()` and `Video.setModuleLogLevel()` don't seem to affect the logs from `tvi.webrtc.EglRenderer`. The main offender is the statistic logger in that class, which logs `INFO` logs in the following format every 4 seconds per renderer:
```
I/tvi.webrtc.Logging: EglRenderer: video_view_id: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: 0.0. Average render time: NA. Average swapBuffer time: NA.
```

It appears to be using the `fallbackLogger`, which logs everything by default. To turn it off, you can use the following block:
```kotlin
// instantiate a Logger instance so it calls Logging.createFallbackLogger()
Logger()
Logger.getLogger("tvi.webrtc.Logging").apply { level = Level.OFF }
```

Note, we're also using an older version of the SDK (`5.10.0`), so this may be fixed in later versions.

**Comment by lambo81** [comment]
Thanks @marshallaf 

For java it's 
Logger.getLogger("tvi.webrtc.Logging").setLevel(Level.OFF);
