### ISSUE TITLE
localAudioTrack not working while the device goes to sleep mode

### ISSUE THREAD

**Issue by braver-tool** [twilio/video-quickstart-android#606]
### Description  :

We implement Twilio video SDK on my application its working smoothly but have faced some audiotrack issues while the device goes to sleep mode. That means localAudioTrack not working in sleep mode.

### Testing Scenario :

CallerX call CallerY, during the call CallerX's device goes to sleep mode, that time CallerX can hear CallerY's voice, but CallerY can't hear CallerX's audio.  

Twilio SDK version : 6.1.0

Audio Switch : 1.1.0

Testing Device model : Oneplus 7

Os Version : Android 10 

Please give any suggestion or source to fix this issue. Thanks in advance...!

**Comment by Alton09** [comment]
Hi @braver-tool . Thank you for reaching out regarding this issue. Can you further elaborate on sleep mode? Does this mean locking the device? Or does this occur after a certain amount of time while in a Video Room? 

Also, I have verified that in the [Twilio Video App,](https://github.com/twilio/twilio-video-app-android) audio tracks work just fine while locking the screen. We also run a Foreground Service while the room is active on the device in order to ensure the app process is treated as high priority to the system. We highly recommend this approach. Hope that helps!

**Comment by braver-tool** [comment]
Hi @Alton09, first I would like to thank you so much. The issue is fixed now, by using FOREGROUND_SERVICE. [video quickstart application](https://github.com/twilio/video-quickstart-android) does not have that so that I had a little bit of confusion.
