### ISSUE TITLE
Create a github repo with twilio video android releases like iOS has

### ISSUE THREAD

**Issue by 4brunu** [twilio/video-quickstart-android#609]
### Description

I couldn't find a better place for this, so I created this issue here.

There isn't any easy way of subscribing to Twilio Video Android releases.

To subscribe the Twilio Video iOS releases, I can watch the releases of  https://github.com/twilio/twilio-video-ios, and I receive an email each time there is a new release.
Also each Twilio Video iOS release on GitHub has the change log, known issues, size impact, and the download link, which is very convenient.

Here is the Twilio Video iOS release [4.1.0](https://github.com/twilio/twilio-video-ios/releases/tag/4.1.0) as an example.

It would be nice to have something simillar to that, but for Android.

Thanks

**Comment by Alton09** [comment]
Hi @4brunu . Good question, since we publish the Android SDK releases to Bintray you can get notified about new releases by becoming a watcher on the [video-android repository](https://bintray.com/twilio/releases/video-android). Unfortunately it does not contain the changelog updates, but you can always easily reference them via the [Twilio docs](https://www.twilio.com/docs/video/changelog-twilio-video-android-v6). Hope that answers your question. Thanks!

**Comment by Alton09** [comment]
Closing this one for now. Please feel free to reach out for any additional requests. Thanks!

**Comment by 4brunu** [comment]
I would prefeer a github repo like the iOS one, but I understand your points 👍 
Thanks for the replying 🙂

**Comment by 4brunu** [comment]
@Alton09 now that Bintray is being sunset, and will not receive any new packages update, is there any recommended way to receive notifications when a new version of Twilio Video Android SDK is available?
I'm not sure if maybe https://mvnrepository.com/artifact/com.twilio/video-android has the same functionality of getting notified about new releases? 
Thanks

**Comment by Alton09** [comment]
Hi @4brunu ! I'm not aware of a mechanism to get notified about new releases directly from Maven Central. However, this website, https://www.artifact-listener.org/, allows you to get notifications for any artifact hosted on Maven Central. Hope that helps!
