### ISSUE TITLE
Record Audio when conversation running

### ISSUE THREAD

**Issue by phongnx** [twilio/video-quickstart-android#62]
Dear,
I have an issue when conversation running, I can't record audio because I can't set AudioSource - Mic: mMediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC)
maybe it was conflicted with Twilio.
Can you give me about a your solution for my problem?
Thanks!

**Comment by aaalaniz** [comment]
Hey @phongnx 

When a `LocalAudioTrack` is added to `LocalMedia` an [AudioTrack](https://developer.android.com/reference/android/media/AudioTrack.html) is created. This audio track streams audio from the microphone and is causing your conflict because the microphone resource can only be acquired once. If you would like to record audio while connected to a `Room` you will have to call `LocalMedia#removeAudioTrack` to free the microphone resource. However, this will stop the audio be shared to a `Room`.

We are currently working on a media recording feature for the Video SDK. The feature is in development and should be made available later this year. Let me know if I can clarify any of the information.

Thanks

**Comment by aaalaniz** [comment]
Let me add some more explanation for how the recording feature is being developed. 

The recording feature will be implemented server side and will allow developers to obtain video and audio tracks via a REST API.

**Comment by phongnx** [comment]
Dear,
Thanks for your answers, I hope this feature will available sooner. :)

**Comment by tungns2408** [comment]
@aaalaniz 
May you help me clear more about current status of recording feature.
>Let me add some more explanation for how the recording feature is being developed.
>
>The recording feature will be implemented server side and will allow developers to obtain video and >audio tracks via a REST API.
=> You mean currently I can get the audio record from REST API right?

**Comment by aaalaniz** [comment]
Hey @tungns2408 

The Video recording feature is not available to developers right now so you cannot access tracks via the REST API. 

Let me clarify the status of the recording feature. We are currently working on a server-side implementation of recording. Developers will be able to record the media being shared to a `Room` and access the recorded audio and video tracks via a REST API. This feature is still in development, and will be made available later this year.

Let me know if I can clarify anything else. Thanks!

**Comment by ktoraskartwilio** [comment]
Hi @phongnx @tungns2408 

Twilio Video Recordings is now available in a Developer Preview along with Group Rooms (multi-party video sessions). Please reach out to me at (ktoraskar@twilio.com) with your account SID and a short description of your use case. Would be happy to enable Recordings on your account.

Thanks,

**Comment by idelgado** [comment]
Please let us know if you have additional questions about recordings.

**Comment by vnext-tungns** [comment]
@idelgado Thank you a lot, let us try it.

**Comment by phuochau** [comment]
Hi @aaalaniz with current Video SDK, can we switch from default `MediaRecorder.AudioSource.VOICE_COMMUNICATION` to another AudioSource? Thanks

**Comment by aaalaniz** [comment]
Hey @phongnx 

The Video Android SDK does not support switching the default AudioSource today. What is your use case for switching the default source?

Thanks!
