### ISSUE TITLE
Participant disconnect event is fired too late

### ISSUE THREAD

**Issue by matdennoigi** [twilio/video-quickstart-android#80]
Hi guys,

We developed a video call app with Twilio. In a call, assume has 2 participants A & B. When device of A be crashed or lost network, after 1 minutes and 13 seconds later, Twilio (on A device) threw "B disconnect" event. How can I make it faster, because our service charge over call duration?

**Comment by idelgado** [comment]
@matdennoigi We have an issue in our backend infrastructure at the moment, where a timer, that can last up to 120 seconds retains the instance of the participant. We are working through possible solutions to detect and reap participants on abrupt disconnections(crashes, lost network).

I'll update this ticket with the proposal we land on and with an ETA for a fix.

**Comment by matdennoigi** [comment]
Thank so much! Hope it soon

**Comment by moksamedia** [comment]
Any update on this?

**Comment by aaalaniz** [comment]
Hey @moksamedia 

Unfortunately, we have no update on the underlying issue caused by the 120 second timer. However, we did release a new [Participant REST API](https://www.twilio.com/docs/api/video/participants) that allows developers to disconnect participants. If you have a way to detect a participant abruptly dropping (crash, etc) then you could boot that participant from the room using this new API in your backend service. This is not ideal, but it's somewhat of a workaround until we can resolve the timer issue on our backend.

Thanks!

**Comment by Puneet2412** [comment]
Any update on this?

**Comment by aaalaniz** [comment]
Hey @Puneet2412 

Unfortunately, there is no update on this issue.

**Comment by jimmylogic** [comment]
is there any update

**Comment by MattBlack01** [comment]
any update on this?

**Comment by zackm0571** [comment]
Hey @MattBlack01 @jimmylogic  No update. With TCMP this issue will improved but we don’t have a timeline for that yet

**Comment by taher-mosbah** [comment]
Any ETA on a fix or a workaround please ?

**Comment by zackm0571** [comment]
It's on our roadmap and we're actively working on this. I'll provide an update once it's available.

**Comment by RapidoBots** [comment]
Has this issue resolved in the latest 2.0.0 version?
